version: '3'

services:
  cache:
    image: memcached

  api:
    build: ./backend
    command: >
      gunicorn -w 4 -b 0.0.0.0:8000
        --env ENVDIR=envdir.compose
        --access-logfile -
        --reload
        "flaskapp:create_app()"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - cache
    environment:
      PYTHONUNBUFFERED: 'true'

  frontend:
    build: ./frontend
    command: nginx -g "daemon off;"
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "80:80"
    depends_on:
      - api 
