version: '3'

services:
  cache:
    image: memcached
  api:
    build: .
    command: >
      gunicorn -w 4 -b 0.0.0.0:8000
        --env ENVDIR=envdir.compose
        --access-logfile -
        --reload
        "flaskapp:create_app()"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - cache
    environment:
      PYTHONUNBUFFERED: 'true'
